services:
  techxercise_db:
    image: mysql
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\gilma\techxercise:/var/lib/techxercise
    environment:
      MYSQL_USER: phnx
      MYSQL_PASSWORD: PHNX
      MYSQL_DATABASE: techxercise_db
      MYSQL_ROOT_PASSWORD: PHNX
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  techXercise:
    image: techxercise
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: PHNX
      SPRING_DATASOURCE_URL: 'jdbc:mysql://techxercise_db:3306/techxercise_db'
    depends_on:
      techxercise_db:
        condition: service_healthy
